use_frameworks!

platform :ios, '11.0'

target 'HYUKSDK_Example' do
  pod 'HYUKSDK', :path => '../'
#  pod 'HYUKApiSdk',:git =>"https://github.com/huboceanLi/HYUKApiSdk.git"

  post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end

  target 'HYUKSDK_Tests' do
    inherit! :search_paths

    
  end
end
